# Generated by Django 5.2.12 on 2026-03-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='anonymizedpoint',
            new_name='anonymizer__traject_4a33f1_idx',
            old_name='anonymizer_traject_5c2b2e_idx',
        ),
        migrations.AddField(
            model_name='anonymizationrun',
            name='dp_delta',
            field=models.FloatField(default=1e-05),
        ),
        migrations.AddField(
            model_name='anonymizationrun',
            name='dp_epsilon',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='anonymizationrun',
            name='enable_differential_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anonymizationrun',
            name='enable_pattern_obfuscation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anonymizationrun',
            name='enable_semantic_generalization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anonymizationrun',
            name='pattern_obfuscation_strength',
            field=models.FloatField(default=0.3),
        ),
    ]
